# Generated by Django 5.1.7 on 2025-03-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_homepagecarouselimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecarouselimage',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
