# Generated by Django 5.1.7 on 2025-03-17 23:27

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0002_remove_flex_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='flex',
            name='content',
            field=wagtail.fields.StreamField([('title_and_text', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Add your title', 'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'help_text': 'Add additional text', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 1)]], {})}, null=True),
        ),
    ]
