# Generated by Django 5.1.7 on 2025-03-27 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='The email address of the subscriber.', max_length=100)),
                ('full_name', models.CharField(help_text='First and last name of the subscriber.', max_length=100, null=True)),
            ],
        ),
    ]
