# Generated by Django 5.1.7 on 2025-03-26 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, help_text='Your Facebook profile URL', null=True)),
                ('x', models.URLField(blank=True, help_text='Your X profile URL', null=True)),
                ('linkedin', models.URLField(blank=True, help_text='Your LinkedIn profile URL', null=True)),
                ('instagram', models.URLField(blank=True, help_text='Your Instagram profile URL', null=True)),
                ('youtube', models.URLField(blank=True, help_text='Your YouTube profile URL', null=True)),
                ('pinterest', models.URLField(blank=True, help_text='Your Pinterest profile URL', null=True)),
                ('kaggle', models.URLField(blank=True, help_text='Your Kaggle profile URL', null=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Social Media Settings',
                'verbose_name_plural': 'Social Media Settings',
            },
        ),
    ]
