# Generated by Django 5.1.7 on 2025-03-26 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediasettings',
            name='github',
            field=models.URLField(blank=True, help_text='Your GitHub profile URL', null=True),
        ),
    ]
