# Generated by Django 5.1.7 on 2025-04-10 20:46

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogcategory_alter_blogauthorsorderable_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetailpage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='blog_categories', to='blog.blogcategory'),
        ),
    ]
