# Generated by Django 5.1.7 on 2025-04-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_videoblogpage_youtube_video_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoblogpage',
            name='youtube_video_id',
        ),
        migrations.AddField(
            model_name='videoblogpage',
            name='youtube_video_url',
            field=models.URLField(blank=True, help_text='Youtube video URL', max_length=255, null=True),
        ),
    ]
