# Generated by Django 5.1.7 on 2025-04-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_videoblogpage_youtube_video_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoblogpage',
            name='youtube_video_url',
        ),
        migrations.AddField(
            model_name='videoblogpage',
            name='youtube_video_id',
            field=models.URLField(blank=True, help_text='Youtube video ID', max_length=30, null=True),
        ),
    ]
