# Generated by Django 5.1.7 on 2025-04-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_videoblogpage_youtube_video_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoblogpage',
            name='youtube_video_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
